### ISSUE TITLE
Already extending Request object

### ISSUE THREAD

**Issue by bencagri** [jamzed/steem-php#4]
you are already extending `Request` object. 

why you are using
`return (new Request)->execute('get_account_count', []);`

instead of
`return $this->execute('get_account_count', []);`

?

**Comment by jamzed** [comment]
Hey, 

Thank you for your code review ;-) 

I created this "API" for small project I'm working on and didn't suspect that someone else will find this code :) but I'm really happy with your report, I removed this duplication :)
